baseURL = 'https://tarakhs.github.io/blog/'
languageCode = 'en-us'
title = 'SW Blogpost'
theme = 'ananke'


googleAnalytics = ""
enableRobotsTXT = true

[[params.ananke_socials]]
name = "github"
url = "https://github.com/Tarakhs"
